-- REM-0539 R2: durable, tenant-scoped outbox.
--
-- This migration is additive. Legacy outbox rows are retained and made
-- visible only to an explicit quarantine workflow; no event is deleted.

-- 0001 may already have installed a NOT VALID tenant check. It still applies
-- to UPDATEs, so remove that legacy check while classifying old null-tenant
-- rows; the durable check is recreated below after quarantine.
--
-- 0001 also forces RLS on the legacy tables. The migration role is a dedicated
-- schema owner, so temporarily remove FORCE while this transaction performs
-- deterministic backfill/quarantine. FORCE is restored at the end; a runtime
-- role never executes this migration path.
DO $$
BEGIN
  IF to_regclass('outbox_events') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE outbox_events NO FORCE ROW LEVEL SECURITY';
  END IF;
  IF to_regclass('audit_events') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE audit_events NO FORCE ROW LEVEL SECURITY';
  END IF;
END $$;

ALTER TABLE outbox_events
  DROP CONSTRAINT IF EXISTS outbox_events_tenant_id_not_null;

ALTER TABLE outbox_events
  ADD COLUMN IF NOT EXISTS tenant_id text,
  ADD COLUMN IF NOT EXISTS envelope_version integer,
  ADD COLUMN IF NOT EXISTS correlation_id text,
  ADD COLUMN IF NOT EXISTS idempotency_key text,
  ADD COLUMN IF NOT EXISTS conversation_id text,
  ADD COLUMN IF NOT EXISTS session_id text,
  ADD COLUMN IF NOT EXISTS agent_id text,
  ADD COLUMN IF NOT EXISTS agent_version_id text,
  ADD COLUMN IF NOT EXISTS inbound_message_id text,
  ADD COLUMN IF NOT EXISTS available_at timestamptz,
  ADD COLUMN IF NOT EXISTS attempts integer,
  ADD COLUMN IF NOT EXISTS lease_owner text,
  ADD COLUMN IF NOT EXISTS lease_until timestamptz,
  ADD COLUMN IF NOT EXISTS last_error text,
  ADD COLUMN IF NOT EXISTS processed_at timestamptz,
  ADD COLUMN IF NOT EXISTS dead_lettered_at timestamptz,
  ADD COLUMN IF NOT EXISTS parent_event_id text,
  ADD COLUMN IF NOT EXISTS tenant_isolation_quarantined boolean;

ALTER TABLE outbox_events
  ALTER COLUMN envelope_version SET DEFAULT 1,
  ALTER COLUMN attempts SET DEFAULT 0,
  ALTER COLUMN tenant_isolation_quarantined SET DEFAULT false;

UPDATE outbox_events
SET envelope_version = COALESCE(envelope_version, 1),
    correlation_id = COALESCE(
      correlation_id,
      'corr_00000000-0000-4000-8000-' || substr(md5(id), 1, 12)
    ),
    idempotency_key = COALESCE(idempotency_key, 'legacy:' || id),
    attempts = COALESCE(attempts, 0),
    tenant_isolation_quarantined = COALESCE(tenant_isolation_quarantined, false)
WHERE envelope_version IS NULL
   OR correlation_id IS NULL
   OR idempotency_key IS NULL
   OR attempts IS NULL
   OR tenant_isolation_quarantined IS NULL;

CREATE TABLE IF NOT EXISTS outbox_quarantine (
  event_id text NOT NULL,
  tenant_id text,
  reason text NOT NULL,
  captured_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (event_id, reason)
);

CREATE TABLE IF NOT EXISTS outbox_effects (
  tenant_id text NOT NULL,
  idempotency_key text NOT NULL,
  event_id text NOT NULL,
  result jsonb NOT NULL,
  applied_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, idempotency_key),
  UNIQUE (tenant_id, event_id)
);

CREATE TABLE IF NOT EXISTS outbox_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id text NOT NULL,
  event_id text NOT NULL,
  attempt integer NOT NULL CHECK (attempt > 0),
  worker_id text NOT NULL,
  claimed_at timestamptz NOT NULL DEFAULT now(),
  outcome text,
  error text
);

-- An identity key is unique within a tenant. NULL legacy tenants remain
-- addressable for quarantine and do not participate in new enqueue calls.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE connamespace = current_schema()::regnamespace
      AND conname = 'outbox_events_tenant_id_id_key'
  ) THEN
    ALTER TABLE outbox_events
      ADD CONSTRAINT outbox_events_tenant_id_id_key UNIQUE (tenant_id, id);
  END IF;
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE connamespace = current_schema()::regnamespace
      AND conname = 'outbox_events_tenant_id_idempotency_key_key'
  ) THEN
    ALTER TABLE outbox_events
      ADD CONSTRAINT outbox_events_tenant_id_idempotency_key_key
      UNIQUE (tenant_id, idempotency_key);
  END IF;
END $$;

-- Journal and attempt rows must always point at the same tenant-owned event.
-- `NOT VALID` keeps this additive for a legacy database; new writes are
-- enforced immediately and an operator can validate after remediation.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE connamespace = current_schema()::regnamespace
      AND conname = 'outbox_effects_tenant_event_fk'
  ) THEN
    ALTER TABLE outbox_effects
      ADD CONSTRAINT outbox_effects_tenant_event_fk
      FOREIGN KEY (tenant_id, event_id)
      REFERENCES outbox_events (tenant_id, id)
      NOT VALID;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE connamespace = current_schema()::regnamespace
      AND conname = 'outbox_attempts_tenant_event_fk'
  ) THEN
    ALTER TABLE outbox_attempts
      ADD CONSTRAINT outbox_attempts_tenant_event_fk
      FOREIGN KEY (tenant_id, event_id)
      REFERENCES outbox_events (tenant_id, id)
      NOT VALID;
  END IF;
END $$;

-- The old status check did not include processing/dead_letter. New writes are
-- checked immediately; historical rows are remediated below in this same
-- transaction before the check is validated by a future maintenance action.
ALTER TABLE outbox_events DROP CONSTRAINT IF EXISTS outbox_events_status_check;
ALTER TABLE outbox_events
  ADD CONSTRAINT outbox_events_status_check
  CHECK (status IN ('pending', 'processing', 'processed', 'failed', 'dead_letter'))
  NOT VALID;

-- Capture legacy states that cannot satisfy the durable invariants. The event
-- row remains in place and is terminalized with a redacted reason.
INSERT INTO outbox_quarantine (event_id, tenant_id, reason)
SELECT id, tenant_id, 'legacy_processed_without_effect_journal'
FROM outbox_events AS event
WHERE event.status = 'processed'
  AND NOT EXISTS (
    SELECT 1
    FROM outbox_effects AS effect
    WHERE effect.tenant_id = event.tenant_id
      AND effect.event_id = event.id
  )
ON CONFLICT (event_id, reason) DO NOTHING;

INSERT INTO outbox_quarantine (event_id, tenant_id, reason)
SELECT id, tenant_id, 'legacy_failed_without_retry_time'
FROM outbox_events AS event
WHERE event.status = 'failed'
  AND event.available_at IS NULL
ON CONFLICT (event_id, reason) DO NOTHING;

INSERT INTO outbox_quarantine (event_id, tenant_id, reason)
SELECT id, tenant_id, 'legacy_outbox_missing_tenant'
FROM outbox_events AS event
WHERE event.tenant_id IS NULL
ON CONFLICT (event_id, reason) DO NOTHING;

UPDATE outbox_events AS event
SET status = 'dead_letter',
    attempts = GREATEST(COALESCE(event.attempts, 0), 1),
    last_error = CASE
      WHEN event.tenant_id IS NULL THEN 'legacy_outbox_missing_tenant'
      WHEN event.status = 'processed' THEN 'legacy_processed_without_effect_journal'
      WHEN event.status = 'failed' AND event.available_at IS NULL THEN 'legacy_failed_without_retry_time'
      ELSE event.last_error
    END,
    dead_lettered_at = COALESCE(event.dead_lettered_at, now()),
    lease_owner = NULL,
    lease_until = NULL
WHERE event.tenant_id IS NULL
   OR (event.status = 'processed' AND NOT EXISTS (
        SELECT 1
        FROM outbox_effects AS effect
        WHERE effect.tenant_id = event.tenant_id
          AND effect.event_id = event.id
      ))
   OR (event.status = 'failed' AND event.available_at IS NULL);

UPDATE outbox_events
SET available_at = COALESCE(available_at, created_at, now())
WHERE available_at IS NULL;

-- Every legacy terminalization with a known tenant receives a redacted,
-- tenant-scoped audit event in the same migration transaction. Rows with no
-- tenant remain only in quarantine because the audit contract forbids a null
-- tenant; assigning them a synthetic tenant would destroy ownership evidence.
INSERT INTO audit_events
  (tenant_id, id, type, actor_type, actor_id, correlation_id,
   policy_version, payload, created_at)
SELECT event.tenant_id,
       'audit_outbox_migration_' || substr(md5(event.id || event.last_error), 1, 24),
       'integration_event',
       'System',
       'migration:0010_outbox_durability',
       event.correlation_id,
       'outbox-r2-migration',
       jsonb_build_object(
         'eventId', event.id,
         'status', event.status,
         'action', 'legacy_terminalization',
         'reason', event.last_error
       ),
       now()
FROM outbox_events AS event
WHERE event.tenant_id IS NOT NULL
  AND event.status = 'dead_letter'
  AND event.last_error IN (
    'legacy_outbox_missing_tenant',
    'legacy_processed_without_effect_journal',
    'legacy_failed_without_retry_time'
  )
  AND NOT EXISTS (
    SELECT 1
    FROM audit_events AS audit
    WHERE audit.tenant_id = event.tenant_id
      AND audit.payload->>'eventId' = event.id
      AND audit.payload->>'action' = 'legacy_terminalization'
  );

ALTER TABLE outbox_events
  ALTER COLUMN envelope_version SET NOT NULL,
  ALTER COLUMN correlation_id SET NOT NULL,
  ALTER COLUMN idempotency_key SET NOT NULL,
  ALTER COLUMN available_at SET NOT NULL,
  ALTER COLUMN attempts SET NOT NULL,
  ALTER COLUMN tenant_isolation_quarantined SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE connamespace = current_schema()::regnamespace
      AND conname = 'outbox_events_tenant_id_not_null'
  ) THEN
    ALTER TABLE outbox_events
      ADD CONSTRAINT outbox_events_tenant_id_not_null
      CHECK (tenant_id IS NOT NULL) NOT VALID;
  END IF;
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE connamespace = current_schema()::regnamespace
      AND conname = 'outbox_events_attempts_check'
  ) THEN
    ALTER TABLE outbox_events
      ADD CONSTRAINT outbox_events_attempts_check CHECK (attempts >= 0) NOT VALID;
  END IF;
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE connamespace = current_schema()::regnamespace
      AND conname = 'outbox_events_processing_lease_check'
  ) THEN
    ALTER TABLE outbox_events
      ADD CONSTRAINT outbox_events_processing_lease_check
      CHECK (
        status <> 'processing'
        OR (lease_owner IS NOT NULL AND lease_until IS NOT NULL)
      ) NOT VALID;
  END IF;
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE connamespace = current_schema()::regnamespace
      AND conname = 'outbox_events_failed_available_check'
  ) THEN
    ALTER TABLE outbox_events
      ADD CONSTRAINT outbox_events_failed_available_check
      CHECK (status <> 'failed' OR available_at IS NOT NULL) NOT VALID;
  END IF;
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE connamespace = current_schema()::regnamespace
      AND conname = 'outbox_events_dead_letter_check'
  ) THEN
    ALTER TABLE outbox_events
      ADD CONSTRAINT outbox_events_dead_letter_check
      CHECK (
        status <> 'dead_letter'
        OR (attempts > 0 AND last_error IS NOT NULL AND dead_lettered_at IS NOT NULL)
      ) NOT VALID;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_outbox_events_tenant_status_available
  ON outbox_events (tenant_id, status, available_at);
CREATE INDEX IF NOT EXISTS idx_outbox_events_tenant_lease
  ON outbox_events (tenant_id, lease_until)
  WHERE status = 'processing';
CREATE INDEX IF NOT EXISTS idx_outbox_effects_tenant_event
  ON outbox_effects (tenant_id, event_id);
CREATE INDEX IF NOT EXISTS idx_outbox_attempts_tenant_event
  ON outbox_attempts (tenant_id, event_id, claimed_at DESC);
CREATE INDEX IF NOT EXISTS idx_outbox_quarantine_tenant_captured
  ON outbox_quarantine (tenant_id, captured_at DESC);

ALTER TABLE outbox_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE outbox_events FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_events FORCE ROW LEVEL SECURITY;
ALTER TABLE outbox_effects ENABLE ROW LEVEL SECURITY;
ALTER TABLE outbox_effects FORCE ROW LEVEL SECURITY;
ALTER TABLE outbox_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE outbox_attempts FORCE ROW LEVEL SECURITY;
ALTER TABLE outbox_quarantine ENABLE ROW LEVEL SECURITY;
ALTER TABLE outbox_quarantine FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS outbox_events_tenant_isolation ON outbox_events;
CREATE POLICY outbox_events_tenant_isolation ON outbox_events
  USING (
    tenant_isolation_quarantined = false
    AND tenant_id = NULLIF(current_setting('cvg.tenant_id', true), '')
  )
  WITH CHECK (
    tenant_isolation_quarantined = false
    AND tenant_id = NULLIF(current_setting('cvg.tenant_id', true), '')
  );

DROP POLICY IF EXISTS outbox_effects_tenant_isolation ON outbox_effects;
CREATE POLICY outbox_effects_tenant_isolation ON outbox_effects
  USING (tenant_id = NULLIF(current_setting('cvg.tenant_id', true), ''))
  WITH CHECK (tenant_id = NULLIF(current_setting('cvg.tenant_id', true), ''));

DROP POLICY IF EXISTS outbox_attempts_tenant_isolation ON outbox_attempts;
CREATE POLICY outbox_attempts_tenant_isolation ON outbox_attempts
  USING (tenant_id = NULLIF(current_setting('cvg.tenant_id', true), ''))
  WITH CHECK (tenant_id = NULLIF(current_setting('cvg.tenant_id', true), ''));

DROP POLICY IF EXISTS outbox_quarantine_tenant_isolation ON outbox_quarantine;
CREATE POLICY outbox_quarantine_tenant_isolation ON outbox_quarantine
  USING (tenant_id = NULLIF(current_setting('cvg.tenant_id', true), ''))
  WITH CHECK (tenant_id = NULLIF(current_setting('cvg.tenant_id', true), ''));

COMMENT ON TABLE outbox_events IS
  'Tenant-scoped durable outbox. Processing is at-least-once; local effects use outbox_effects for idempotency.';
COMMENT ON TABLE outbox_attempts IS
  'Append-only claim history for durable outbox events; rows are never deleted during retry or requeue.';
COMMENT ON TABLE outbox_quarantine IS
  'Legacy outbox rows that cannot satisfy durable tenant/effect invariants; retained for explicit remediation.';
